# Generated by Django 5.0.7 on 2024-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Custom', 'Custom'), ('Female', 'Female')], max_length=100),
        ),
    ]
