# Generated by Django 5.0.7 on 2024-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('current', 'current'), ('savings', 'savings')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
