# Generated by Django 5.0.7 on 2024-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings'), ('current', 'current')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Custom', 'Custom'), ('Female', 'Female')], max_length=100),
        ),
    ]
