# Generated by Django 5.0.7 on 2024-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings'), ('current', 'current')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/staticfiles/uploads'),
        ),
    ]
