# Generated by Django 5.0.7 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Custom', 'Custom'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/media/uploads'),
        ),
    ]
